# Generated by Django 4.1.5 on 2023-02-02 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0007_remove_product_seller_delete_person_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=100)),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('number', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('price', models.TextField()),
                ('image', models.TextField()),
                ('states', models.TextField()),
                ('city', models.TextField()),
                ('isDeliver', models.TextField()),
                ('cartype', models.TextField()),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.person')),
            ],
        ),
    ]
