# Generated by Django 4.1.5 on 2023-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.TextField(default=0),
        ),
    ]
