# Generated by Django 4.1.5 on 2023-02-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_product_likes_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to='apps.person'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='apps.person'),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.ManyToManyField(related_name='views', to='apps.person'),
        ),
    ]
