# Generated by Django 4.1.5 on 2023-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_product_likes_alter_product_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='liked',
            field=models.ManyToManyField(related_name='liked_by', to='apps.product'),
        ),
    ]
