# Generated by Django 4.1.5 on 2023-02-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
