# Generated by Django 4.1.5 on 2023-02-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_message_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isBest',
            field=models.TextField(default=0, null=True),
        ),
    ]
