# Generated by Django 4.1.5 on 2023-02-17 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_product_isbest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='apps.person')),
                ('person1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='apps.person')),
                ('person2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='apps.person')),
            ],
        ),
    ]
