# Generated by Django 4.1.5 on 2023-02-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_personmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmessage',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
