# Generated by Django 4.1.5 on 2023-02-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_personmessage_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmessage',
            old_name='person2',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='personmessage',
            old_name='person1',
            new_name='sender',
        ),
    ]
