# Generated by Django 4.1.5 on 2023-02-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_rename_person2_personmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personmessage',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='personmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
